### ISSUE TITLE
Explorer UI takes 15 seconds to load on first visit after app start

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-explorer#633]
If we cannot make it faster, we need a loading splash.

**Comment by ComLock** [comment]
- [ ] Perhaps execute the graphql schema after init

**Comment by ComLock** [comment]
We've had a meeting to discuss this, and it turns out, the 15 seconds between main.js logging and tasks/init.js logging disappears if one makes the init.js small.

So, what needs to "block the admin ui" and run on every startup should be as small as possible.
Migrations, which may run for hours, should be a separate "non-blocking" task.
