### ISSUE TITLE
Spelling mistakes in phrases (in progress)

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-explorer#635]
- [x] Collection name - "Please input an unique name" - > "Please input a unique name"
- [x] Label for webcrawler form "Uri" -> "URL"

**Comment by ComLock** [comment]
It turns out you are right it's `a unique`

`Some words that are spelled with U begin with the sound Y (/j/ in IPA.)Those words are considered consonants and use a:

a union, a unicorn, a uniform, a unique gift.

When words spelled with U sound like /uw/, than it’s a vowel, adn so an:

an umbrella, an uncle, an undershirt, an upside-down cake.`
