### ISSUE TITLE
Webcrawler: Support custom http request headers

### ISSUE THREAD

**Issue by ComLock** [enonic/app-explorer#898]
https://enonic.zendesk.com/agent/tickets/6839

From before we have user_agent. Changing json structure might be a breaking change...

Perhaps have a blacklist. @rymsha Do you have an opinion?

**Comment by rymsha** [comment]
There is certainly a limit of which headers can be used. Some headers must not be manipulated ever - because they are transport related (for instance "connection", "content-length", "host", "upgrade", "Transfer-Encoding"), 
others are allowed in http 1.1, but not in h2

`Authorization` and `Proxy-Authorization` should not be manipulated directly either.

**Comment by ComLock** [comment]
Hmm, Authorization is one of the ones used regularly in the Surgeon Collector, so how else should it be set?

It's even used in this example:
https://developer.enonic.com/docs/http-client-library/stable#using_custom_certificate

**Comment by rymsha** [comment]
My bad. Yes it is now possible to set explicitly via headers
